namespace YiJingFramework.FiveElements
{
    /// <summary>
    /// 五行之间的关系。
    /// The relationships between the five elements.
    /// </summary>
    public enum FiveElementsRelationship
    {
        /// <summary>
        /// 同“我”者。
        /// The element that is the same as 'me'.
        /// </summary>
        SameAsMe = 0,
        /// <summary>
        /// 生“我”者。
        /// The element that generates 'me'.
        /// </summary>
        GeneratingMe = -1 + 5,
        /// <summary>
        /// “我”生者。
        /// The element generated by 'me'.
        /// </summary>
        GeneratedByMe = +1,
        /// <summary>
        /// “我”克者。
        /// The element overcame by 'me'.
        /// </summary>
        OvercameByMe = +2,
        /// <summary>
        /// 克“我”者。
        /// The element that overcomes 'me'.
        /// </summary>
        OvercomingMe = -2 + 5,
    }
}
